module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
    diodeIMPROVED: require('./tap4Footprints/diodeIMPROVED'),
    buzzer12: require('./tap4Footprints/buzzer12'),
    mxFix: require('./tap4Footprints/mxFix'),
    chocFix: require('./tap4Footprints/chocFix'),
    duck560: require('./tap4Footprints/duck560'),
    smd_resistor: require('./tap4Footprints/smd_resistorFix'),
    MCUEliteNano: require('./tap4Footprints/MCUEliteNano'),
    azoteq_tps43: require('./tap4Footprints/azoteq_tps43'),
    pinheaders: require('./tap4Footprints/pinheaders'),
    LEDBreakoutPins: require('./tap4Footprints/LEDBreakoutPins'),
    nice_nano: require('./tap4Footprints/nice_nano'),
    reset_switch_smd_side: require('./tap4Footprints/reset_switch_smd_side'),
    nice_view: require('./tap4Footprints/nice_view'),
    mounting_hole_npth: require('./tap4Footprints/mounting_hole_npth'),
    MvEerd_mountinghole: require('./tap4Footprints/MvEerd_mountinghole'),
    M3Mounting: require('./tap4Footprints/M3Mounting'),
    
}